# Generated by Django 5.1.6 on 2025-02-26 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchallengesession',
            name='created_at',
        ),
        migrations.AddField(
            model_name='userchallengesession',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
