# Generated by Django 5.1.6 on 2025-02-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_remove_userchallengesession_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchallengesession',
            old_name='create_time',
            new_name='start_time',
        ),
    ]
