# Generated by Django 5.1.6 on 2025-02-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_rename_create_time_userchallengesession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
