# Generated by Django 5.1.6 on 2025-03-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_userprogress_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='score_increase',
            field=models.IntegerField(default=0),
        ),
    ]
