# Generated by Django 5.1.6 on 2025-02-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='input_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='min_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='output_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='total_testcases',
            field=models.IntegerField(default=0),
        ),
    ]
