# Generated by Django 5.1.6 on 2025-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenges_constraints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='total_testcases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
